services:
  model-service:
    build: ../model-service
    ports:
      - "5010:5010"
    environment:
      - MODEL_URL=https://github.com/remla2025-team16/model-training/releases/download/v1.0.0/sentiment-model.pkl
  app-frontend:
    build:
      context: ../app/app-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  app-service:
    build: 
      context: ../app/app-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MODEL_SERVICE_URL=http://model-service:5010
