services:
  model-service:
    build: ../model-service
    ports:
      - "5010:5010"
  frontend:
    build:
      context: ../app-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  app-service:
    build: 
      context: ../app-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MODEL_SERVICE_URL=http://model-service:5010
