services:
  model-service:
    build: ../model-service
    expose:
      - "5010"
    environment:
      - MODEL_URL=${MODEL_URL}
    networks:
      - appnet
  app-frontend:
    build:
      context: ../app/app-frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - appnet
  app-service:
    build: 
      context: ../app/app-service
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - MODEL_SERVICE_URL=${MODEL_SERVICE_URL}
    networks:
      - appnet
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" 
    depends_on:
      - model-service
      - app-service
      - app-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge