services:
  model-service:
    build: ../model-service
    ports:
      - "5010:5010"
    environment:
      - MODEL_URL=${MODEL_URL}
  app-frontend:
    build:
      context: ../app/app-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  app-service:
    build: 
      context: ../app/app-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MODEL_SERVICE_URL=${MODEL_SERVICE_URL}

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

