global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app-service'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'model-service'
    static_configs:
      - targets: ['host.docker.internal:5010']
