apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" $ }}-config
  labels:
    {{- include "my-app.labels" $ | nindent 4 }}
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}