{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "my-app.fullname" . }}-servicemonitor
  namespace: {{ .Values.serviceMonitor.prometheusNamespace | default "default" }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      component: app-service
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}
{{- end }}
