apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  model_service_url: http://localhost:5010
  model_url: https://github.com/remla2025-team16/model-training/releases/download/v1.0.0/sentiment-model.pkl
