---
- hosts: all
  become: yes

  tasks:
    # Step 20 - MetalLB
    - name: Apply MetalLB manifests
      command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml

    - name: Wait for MetalLB controller to be ready
      command: >
        kubectl wait -n metallb-system -l app=metallb,component=controller
        --for=condition=ready pod --timeout=60s

    - name: Configure MetalLB IPAddressPool
      copy:
        dest: /tmp/metallb-IP-config.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: default-pool
            namespace: metallb-system
          spec:
            addresses:
            - 192.168.56.90-192.168.56.99

    - name: Apply MetalLB IPAddressPool
      command: kubectl apply -f /tmp/metallb-IP-config.yaml

    - name: Configure MetalLB L2Advertisement
      copy:
        dest: /tmp/metallb-L2-config.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2-ad
            namespace: metallb-system

    - name: Apply MetalLB L2Advertisement
      command: kubectl apply -f /tmp/metallb-L2-config.yaml

    # Step 21 - Ingress NGINX
    - name: Add ingress-nginx Helm repo
      command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Update Helm repos
      command: helm repo update

    - name: Install ingress-nginx
      command: >
        helm install ingress-nginx ingress-nginx/ingress-nginx
        --set controller.service.type=LoadBalancer
        --set controller.service.loadBalancerIP=192.168.56.91

    # Step 22 - Dashboard
    - name: Add Kubernetes Dashboard Helm repo
      command: helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/

    - name: Deploy Kubernetes Dashboard via Helm
      command: >
        helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard
        --create-namespace --namespace kubernetes-dashboard

    - name: Create ServiceAccount and ClusterRoleBinding for admin
      copy:
        dest: /tmp/dashboard-admin.yaml
        content: |
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: admin-user
            namespace: kubernetes-dashboard
          ---
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: admin-user
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: admin-user
            namespace: kubernetes-dashboard

    - name: Apply Dashboard ServiceAccount config
      command: kubectl apply -f /tmp/dashboard-admin.yaml

    - name: Create Ingress for dashboard
      copy:
        dest: /tmp/dashboard-ingress.yaml
        content: |
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: kubernetes-dashboard
            namespace: kubernetes-dashboard
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          spec:
            ingressClassName: nginx
            rules:
            - host: dashboard.local
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: kubernetes-dashboard
                      port:
                        number: 443

    - name: Apply Dashboard Ingress
      command: kubectl apply -f /tmp/dashboard-ingress.yaml

