# ansible/general.yaml
- hosts: all
  become: yes # Most of these tasks require root privileges
  tasks:
    # Step 9: Add Kubernetes repository
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Dependencies 
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
          - lsb-release
          - software-properties-common

    - name: Create directory for Kubernetes GPG
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Kubernetes GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key # or https://packages.cloud.google.com/apt/doc/apt-key.gpg not sure what is correct
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: "0644"
        force: yes 

    - name: Add Kubernetes APT key
      ansible.builtin.apt_key:
        file: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present

    - name: Add Kubernetes APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present
        filename: kubernetes

    # Step 10: Install Kubernetes components
    

