# ansible/general.yaml
- hosts: all
  become: yes # Most of these tasks require root privileges
  tasks:
    # Step 9: Add Kubernetes repository
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Dependencies #making sure all dependencies are installed 
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
          - lsb-release
          - software-properties-common

    - name: Create directory for Kubernetes GPG
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Kubernetes APT key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key 
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present

    - name: Add Kubernetes APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present

    - name: Update apt cache after adding Kubernetes repository
      ansible.builtin.apt:
        update_cache: yes

    # Step 10: Install Kubernetes components
    - name: Install Kubernetes components
      ansible.builtin.apt:
        name:
          - containerd=1.7.24
          - runc=1.1.12
          - kubelet=1.32.4
          - kubeadm=1.32.4
          - kubectl=1.32.4
        state: present
        update_cache: yes

    # Step 11: Configure Containerd
    
