tasks:
	# Step 18
	- name: Join command from controller
	  shell: kubeadm token create --print-join-command
	  register: join_command
	  changed_when: false
	  delegate_to: ctrl

	# Step 19
	- name: Join node to cluster
	  shell: "{{ join_command.stdout }}"
	  args :
    	    creates: /etc/kubernetes/kubelet.conf
    	    
    	    
