---
- name: Configure and Join Kubernetes Worker Nodes
  hosts: nodes
  become: true
  gather_facts: yes

  tasks:
    - name: Check if node has already successfully joined the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf_status

    - name: Get Kubernetes join command from controller
      command: kubeadm token create --print-join-command
      delegate_to: "{{ groups['ctrl'][0] }}"
      run_once: true 
      register: join_command
      when: not kubelet_conf_status.stat.exists


    - name: Join the Kubernetes cluster as a worker node
      ansible.builtin.shell:
        cmd: "{{ join_command.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      register: join_output
      when: not kubelet_conf_status.stat.exists 

    - name: Display kubeadm join output (if applicable)
      debug:
        var: join_output.stdout_lines
      when: join_output.changed is defined and join_output.changed 