tasks:
	# Step 18
	- name: Join command from controller
	  ansible.builtin.command: kubeadm token create --print-join-command
	  register: join_command
	  changed_when: false
	  delegate_to: ctrl
	  run_once: true

	# Step 19
	- name: Join node to cluster
	  ansible.builtin.command: "{{ join_command.stdout }}"
	  args :
    	    creates: /etc/kubernetes/kubelet.conf
    	    
