- hosts: nodes
  serial: 1
  gather_facts: yes

  pre_tasks:
    - name: Ensure kubeadm-flags.env exists (avoid unset variable)
      become: true
      file:
        path: /var/lib/kubelet/kubeadm-flags.env
        state: touch
        owner: root
        group: root
        mode: '0644'
  
  tasks:
    - name: Check if node is already part of the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_config_exists

    - name: Generate Kubernetes join command on controller
      command: kubeadm token create --print-join-command
      delegate_to: "{{ groups['ctrl'][0] }}"
      run_once: true
      register: join_cmd
      when: not kubelet_config_exists.stat.exists
    
    - name: Join the Kubernetes cluster
      ansible.builtin.shell:
        cmd: "{{ join_cmd.stdout }}"
      become: true
      when: not kubelet_config_exists.stat.exists